version: v1
plugins:
  - name: gocosmos
    out: gen
    opt:
      - plugins=grpc
      - Mgoogle/protobuf/any.proto=github.com/cosmos/cosmos-sdk/codec/types
      - Mcosmos/orm/v1/orm.proto=cosmossdk.io/orm
